all:
#	dot -Tps ex1.dot -o ex1.ps
#	ps2epsi ex1.ps
#	mv ex1.epsi ex1.eps
#	dot -Tps inherit.dot -o inherit.ps
#	ps2epsi inherit.ps
#	mv inherit.epsi inherit.eps
	latex paper.tex
	latex paper.tex
	dvips paper.dvi -o paper.ps
