Filter A
Filter B
Filter C amount=0
Filter D pop=0
Filter A
Filter B
Filter C amount=1
	Filter C pop=0
Filter D pop=1
Filter A
Filter B
Filter C amount=2
	Filter C pop=1
	Filter C pop=2
Filter D pop=2
Filter A
Filter B
Filter C amount=3
	Filter C pop=3
	Filter C pop=4
	Filter C pop=5
Filter D pop=3
Filter A
Filter B
Filter C amount=4
	Filter C pop=6
	Filter C pop=7
	Filter C pop=8
	Filter C pop=9
Filter D pop=4
Filter A
Filter B
Filter C amount=5
	Filter C pop=10
	Filter C pop=11
	Filter C pop=12
	Filter C pop=13
	Filter C pop=14
Filter D pop=5
Filter A
Filter B
Filter C amount=6
	Filter C pop=15
	Filter C pop=16
	Filter C pop=17
	Filter C pop=18
	Filter C pop=19
	Filter C pop=20
Filter D pop=6
Filter A
Filter B
Filter C amount=7
	Filter C pop=21
	Filter C pop=22
	Filter C pop=23
	Filter C pop=24
	Filter C pop=25
	Filter C pop=26
	Filter C pop=27
Filter D pop=7
Filter A
Filter B
Filter C amount=8
	Filter C pop=28
	Filter C pop=29
	Filter C pop=30
	Filter C pop=31
	Filter C pop=32
	Filter C pop=33
	Filter C pop=34
	Filter C pop=35
Filter D pop=8
Filter A
Filter B
Filter C amount=9
	Filter C pop=36
	Filter C pop=37
	Filter C pop=38
	Filter C pop=39
	Filter C pop=40
	Filter C pop=41
	Filter C pop=42
	Filter C pop=43
	Filter C pop=44
Filter D pop=9
