Filter A
Filter B
Filter C amount=1
	Filter C pop=0
Filter D pop=0
Filter A
Filter B
Filter C amount=3
	Filter C pop=1
	Filter C pop=2
	Filter C pop=3
Filter D pop=1
Filter A
Filter B
Filter C amount=5
	Filter C pop=4
	Filter C pop=5
	Filter C pop=6
	Filter C pop=7
	Filter C pop=8
Filter D pop=2
Filter A
Filter B
Filter C amount=7
	Filter C pop=9
	Filter C pop=10
	Filter C pop=11
	Filter C pop=12
	Filter C pop=13
	Filter C pop=14
	Filter C pop=15
Filter D pop=3
Filter A
Filter B
Filter C amount=9
	Filter C pop=16
	Filter C pop=17
	Filter C pop=18
	Filter C pop=19
	Filter C pop=20
	Filter C pop=21
	Filter C pop=22
	Filter C pop=23
	Filter C pop=24
Filter D pop=4
Filter A
Filter B
Filter C amount=11
	Filter C pop=25
	Filter C pop=26
	Filter C pop=27
	Filter C pop=28
	Filter C pop=29
	Filter C pop=30
	Filter C pop=31
	Filter C pop=32
	Filter C pop=33
	Filter C pop=34
	Filter C pop=35
Filter D pop=5
Filter A
Filter B
Filter C amount=13
	Filter C pop=36
	Filter C pop=37
	Filter C pop=38
	Filter C pop=39
	Filter C pop=40
	Filter C pop=41
	Filter C pop=42
	Filter C pop=43
	Filter C pop=44
	Filter C pop=45
	Filter C pop=46
	Filter C pop=47
	Filter C pop=48
Filter D pop=6
Filter A
Filter B
Filter C amount=15
	Filter C pop=49
	Filter C pop=50
	Filter C pop=51
	Filter C pop=52
	Filter C pop=53
	Filter C pop=54
	Filter C pop=55
	Filter C pop=56
	Filter C pop=57
	Filter C pop=58
	Filter C pop=59
	Filter C pop=60
	Filter C pop=61
	Filter C pop=62
	Filter C pop=63
Filter D pop=7
Filter A
Filter B
Filter C amount=17
	Filter C pop=64
	Filter C pop=65
	Filter C pop=66
	Filter C pop=67
	Filter C pop=68
	Filter C pop=69
	Filter C pop=70
	Filter C pop=71
	Filter C pop=72
	Filter C pop=73
	Filter C pop=74
	Filter C pop=75
	Filter C pop=76
	Filter C pop=77
	Filter C pop=78
	Filter C pop=79
	Filter C pop=80
Filter D pop=8
Filter A
Filter B
Filter C amount=19
	Filter C pop=81
	Filter C pop=82
	Filter C pop=83
	Filter C pop=84
	Filter C pop=85
	Filter C pop=86
	Filter C pop=87
	Filter C pop=88
	Filter C pop=89
	Filter C pop=90
	Filter C pop=91
	Filter C pop=92
	Filter C pop=93
	Filter C pop=94
	Filter C pop=95
	Filter C pop=96
	Filter C pop=97
	Filter C pop=98
	Filter C pop=99
Filter D pop=9
