</head>

<body>
<table border="0" width="1000" cellpadding="0" align="center">

<tr><td colspan=4>
<table border="0" width="600" cellpadding="2" align="center">
  <tr>
    <td valign="center" align="center">
    <br>
      <img src="../images/streamit-logo.gif" width="400">
      <font color="#FF6633">
        <br><br>
        <nobr><b>
            <a href="../index.shtml"><font color="#000099">home</font></a>
          | <a href="../shtml/news.shtml"><font color="#000099">news</font></a>
          | <a href="../shtml/research.shtml"><font color="#000099">research</font></a>
          | <a href="../shtml/people.shtml"><font color="#000099">people</font></a> 
          | <a href="../shtml/documentation.shtml"><font color="#000099">documentation</font></a>
          | <a href="../shtml/download.shtml"><font color="#000099">download</font></a>
          | <a href="../shtml/links.shtml"><font color="#000099">links</font></a>
          | <a href="../shtml/contact.shtml"><font color="#000099">contact</font></a>
        </nobr></b>
      </font>
    </td>
  </tr>
</table>
</td></tr>
