<!--#include virtual="../include/init.inc"-->
   <style type="text/css">A:hover {color: #000000}</style>
   <meta NAME="author" CONTENT="Matthew H. Drake">
   <title>StreamIt</title>
<!--#include virtual="../include/header-level1.inc"-->

  <tr>
    <td width="130" valign="top" align="left"><b>
      <hr>
      <nobr>
        <h4 align="center">MPEG-2 in StreamIt</h4><hr>
        <a href="./">Home</a><hr>
        <a href="./downloads.shtml">Downloads</a><hr>
        <a href="./features.shtml">Features</a><hr>
        <a href="./decoder.shtml">Decoder</a><hr>
        <a href="./encoder.shtml">Encoder</a><hr>
        <a href="./api.shtml">StreamItDocs</a><hr>
        <a href="./related.shtml">Links</a><hr>
      </nobr>
    </td>

    <td width="20" valign="top" align="left"></td>
    <td width="700" valign="top" align="left">
      <hr>




