package at.dms.kjc.sir;

import at.dms.compiler.PositionedError;
import at.dms.compiler.TokenReference;
import at.dms.kjc.AttributeVisitor;
import at.dms.kjc.CExpressionContext;
import at.dms.kjc.CStdType;
import at.dms.kjc.CType;
import at.dms.kjc.CodeSequence;
import at.dms.kjc.ExpressionVisitor;
import at.dms.kjc.JExpression;
import at.dms.kjc.KjcVisitor;
import at.dms.kjc.SLIRAttributeVisitor;
import at.dms.kjc.SLIRVisitor;

/**
 * This represents a peek expression.
 */
public class SIRPeekExpression extends JExpression {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4980692982732180607L;

	/**
     * The argument to the peek expression--the index of the item to
     * peek.
     */
    protected JExpression arg;

    /**
     * Type of the item to peek.
     */
    protected CType tapeType;

    /**
     * No argument constructor, FOR AUTOMATIC CLONING ONLY.
     */
    protected SIRPeekExpression() {
        super();
    }
    
    /**
     * Construct a node in the parsing tree
     * @param   where       the line of this node in the source code
     * @param   arg     the argument of the call
     */
    public SIRPeekExpression(TokenReference where, JExpression arg)
    {
        super(where);
        this.tapeType = null;
        this.arg = arg;
    }

    /**
     * Construct a node in the parsing tree with null TokenReference
     * @param   arg     the argument of the call
     */
    public SIRPeekExpression(JExpression arg)
    {
        this(arg, null);
    }

    public SIRPeekExpression(JExpression arg, CType tapeType)
    {
        super(null);
        this.tapeType = tapeType;
        this.arg = arg;
    }

    /**
     * Sets the type of the tape being peeked at
     * @param   type             the type of the tape
     */
    public void setTapeType(CType type)
    {
        this.tapeType = type;
    }

    @Override
	public void setType(CType type) {
        setTapeType(type);
    }
    
    /**
     * Sets the arg of this.
     */
    public void setArg(JExpression arg) {
        this.arg = arg;
    }

    /**
     * Returns the argument of this.
     */
    public JExpression getArg() {
        return arg;
    }

    // ----------------------------------------------------------------------
    // ACCESSORS
    // ----------------------------------------------------------------------

    /**
     * @return the type of this expression
     */
    @Override
	public CType getType() {
        if (tapeType != null)
            return tapeType;
        return CStdType.Void;
    }

    /**
     * Returns true iff this expression can be used as a statement (JLS 14.8)
     */
    @Override
	public boolean isStatementExpression() {
        return true;
    }

    // ----------------------------------------------------------------------
    // SEMANTIC ANALYSIS
    // ----------------------------------------------------------------------

    /**
     * Throws an exception (NOT SUPPORTED YET)
     */
    @Override
	public JExpression analyse(CExpressionContext context) throws PositionedError {
        at.dms.util.Utils.fail("Analysis of custom nodes not supported yet.");
        return this;
    }

    // ----------------------------------------------------------------------
    // CODE GENERATION
    // ----------------------------------------------------------------------

    /**
     * Accepts the specified visitor.
     */
    @Override
	public void accept(KjcVisitor p) {
        if (p instanceof SLIRVisitor) {
            ((SLIRVisitor)p).visitPeekExpression(this, tapeType, arg);
        } else {
            // visit the argument
            arg.accept(p);
        }
    }

    /**
     * Accepts the specified attribute visitor.
     * @param   p               the visitor
     */
    @Override
	public Object accept(AttributeVisitor p) {
        if (p instanceof SLIRAttributeVisitor) {
            return ((SLIRAttributeVisitor)p).visitPeekExpression(this,
                                                                 tapeType,
                                                                 arg);
        } else {
            return this;
        }
    }

    /**
     * Accepts the specified visitor
     * @param p the visitor
     * @param o object containing extra data to be passed to visitor
     * @return object containing data generated by visitor 
     */
    @Override
    public <S,T> S accept(ExpressionVisitor<S,T> p, T o) {
        return p.visitPeek(this,o);
    }


    /**
     * Generates JVM bytecode to evaluate this expression.  NOT SUPPORTED YET.
     *
     * @param   code        the bytecode sequence
     * @param   discardValue    discard the result of the evaluation ?
     */
    @Override
	public void genCode(CodeSequence code, boolean discardValue) {
        at.dms.util.Utils.fail("Visitors to custom nodes not supported yet.");
    }

    /**
     * Generates a nice readable version of the PeekExpression.
     **/
    @Override
	public String toString() {
        return ("SIRPeekExpression[" +
                this.arg + "]");
    }
        

    /** THE FOLLOWING SECTION IS AUTO-GENERATED CLONING CODE - DO NOT MODIFY! */

    /** Returns a deep clone of this object. */
    @Override
	public Object deepClone() {
        at.dms.kjc.sir.SIRPeekExpression other = new at.dms.kjc.sir.SIRPeekExpression();
        at.dms.kjc.AutoCloner.register(this, other);
        deepCloneInto(other);
        return other;
    }

    /** Clones all fields of this into <pre>other</pre> */
    protected void deepCloneInto(at.dms.kjc.sir.SIRPeekExpression other) {
        super.deepCloneInto(other);
        other.arg = (at.dms.kjc.JExpression)at.dms.kjc.AutoCloner.cloneToplevel(this.arg);
        other.tapeType = (at.dms.kjc.CType)at.dms.kjc.AutoCloner.cloneToplevel(this.tapeType);
    }

    /** THE PRECEDING SECTION IS AUTO-GENERATED CLONING CODE - DO NOT MODIFY! */
}
