#!/bin/csh
#
# USAGE:  "gather <extra-options> <number to append for input/output files> <label>"
#

$STREAMIT_HOME/misc/scripts/number-gathering/FarmLocal 2 4 "-N 15 -O1 $1" "bench_$2" "results_$3" "$STREAMIT_HOME/docs/pact-03-partition/numbers/blood"
