#!/bin/csh
#
# USAGE:  "gather <extra-ops> <number to append for input/output files>"
#

$STREAMIT_HOME/misc/scripts/number-gathering/FarmLocal 2 5 "-N 10 -u 0 $1" "bench_$2" "results_dp_$2" "$STREAMIT_HOME/docs/spaa-03-load/numbers/blood"
